# Generated by Django 3.1.7 on 2021-03-23 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_auto_20210323_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receitas.chef'),
        ),
    ]
