# Generated by Django 3.1.7 on 2021-03-23 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita_chef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.chef'),
        ),
    ]
